# Repository Structure
# ├── .github/
# │   └── workflows/
# │       └── terraform-deploy.yml
# ├── terraform/
# │   ├── main.tf
# │   ├── variables.tf
# │   └── backend.tf
# └── README.md

# File: .github/workflows/terraform-deploy.yml
name: Terraform AWS Deployment
on:
  push:
    branches:
      - main
      - master
    paths:
      - 'terraform/**'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Format
        working-directory: ./terraform
        run: terraform fmt -check

      - name: Terraform Plan
        working-directory: ./terraform
        #if: github.event_name == 'pull_request'
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./terraform
        #if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve